config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from diadaa.contact import views as contact_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('diadaa.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^analytics/', include('diadaa.analytics.urls', namespace='analytics')),
    # url(r'^apply/', include('diadaa.contact.urls_apply', namespace='apply')),
    url(r'apply/', contact_views.apply_view, name='apply'),
    url(r'^cart/', include('diadaa.cart.urls', namespace='cart')),
    # url(r'^contact/', include('diadaa.contact.urls_contact', namespace='contact')),
    url(r'contact/', contact_views.contact_view, name='contact'),
    url(r'^orders/', include('diadaa.orders.urls', namespace='orders')),
    url(r'^produce/', include('diadaa.produce.urls', namespace='produce')),
    url(r'^logistics/', include('diadaa.logistics.urls', namespace='logistics')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

diadaa/analytics/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.home_view, name='home'),
    url(r'^dashboard/(?P<username>[\w.@+-]+)/$', views.user_dashboard, name='dashboard'),
]

diadaa/cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<produce_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<produce_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

diadaa/orders/urls.py
from django.conf.urls import url
from . import views


urlpatterns = (
    url(r'^bulk/$', views.bulk_demand_create, name='bulk_demand_create'),
    url(r'^create/$', views.order_create, name='order_create'),
)

diadaa/produce/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.ProduceCollectionListView.as_view(), name='produce_collection_list'),
    # url(r'^$', views.ProduceListView.as_view(), name='produce_list'),
    url(r'^categories/$', views.CategoryListView.as_view(), name='category_list'),
    url(r'^categories/(?P<slug>[-\w]+/?)$', views.CategoryDetailView.as_view(), name='category_detail'),
    url(r'^add_produce$', views.produce_create_view, name='produce_create'),
    # url(r'^~(?P<slug>[-\w]+/?)$', views.produce_detail_view, name='produce_detail'),
    url(r'^(?P<name>[-\w]+/?)$', views.produce_collection_detail_view, name='produce_collection_detail'),
    url(r'^~(?P<slug>[-\w]+/?)$', views.ProduceDetailView.as_view(), name='produce_detail'),
    url(r'^~(?P<slug>[-\w]+/?)/update/$', views.ProduceUpdateView.as_view(), name='produce_update'),
]

diadaa/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.MemberTypeListView.as_view(), name='member_type_list'),
    url(r'^~redirect/$', views.UserRedirectView.as_view(), name='redirect'),
    url(r'^~update/$', views.UserUpdateView.as_view(), name='update'),
    url(r'^all/$', views.MemberListView.as_view(), name='member_list'),
    url(r'^agents/$', views.AgentListView.as_view(), name='agent_list'),
    url(r'^consumers/$', views.ConsumerListView.as_view(), name='consumer_list'),
    url(r'^farmers/$', views.FarmerListView.as_view(), name='farmer_list'),
    url(r'^retailers/$', views.RetailerListView.as_view(), name='retailer_list'),
    url(r'^wholesalers/$', views.WholesalerListView.as_view(), name='wholesaler_list'),
    url(r'^(?P<username>[\w.@+-]+)/$', views.UserDetailView.as_view(), name='user_detail'),
    url(r'^~(?P<username>[\w.@+-]+)/$', views.member_detail_view, name='member_detail'),
]

diadaa/cart/models.py
from django.db import models

# Create your models here.

diadaa/contact/models.py
from django.db import models

# Create your models here.

diadaa/cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProduceForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

diadaa/contact/forms.py
from django import forms


class ApplyForm(forms.Form):
    national_id = forms.CharField(max_length=20)
    digital_address = forms.CharField(max_length=20)
    message = forms.CharField(widget=forms.Textarea)  # , verbose_name='Reasons you want to be an agent')


class ContactForm(forms.Form):
    name = forms.CharField(max_length=100, required=False)
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)

diadaa/logistics/forms.py
from django import forms
from django.forms.extras.widgets import SelectDateWidget
from .models import Transport


class TransportForm(forms.ModelForm):
    class Meta:
        model = Transport
        fields = ('vehicle_number', 'departure_region', 'departure_location', #'time_of_departure',
                  'arrival_region', 'arrival_location', 'eta', 'transport_route', 'available_stops',
                  'image', 'capacity', 'availability')
        widgets = {'eta': SelectDateWidget(),
                   'availability': SelectDateWidget()}

diadaa/orders/forms.py
from django import forms
from django.forms.extras.widgets import SelectDateWidget
from .models import Order, BulkDemand


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('first_name', 'last_name', 'email', 'address', 'postal_code', 'city')


class BulkDemandForm(forms.ModelForm):
    class Meta:
        model = BulkDemand
        fields = ('produce', 'quantity', 'start_date', 'periods_needed',
                  'other', 'address', 'digital_address', 'comment')
        widgets = {'start_date': SelectDateWidget()}

diadaa/produce/forms.py
from django import forms
from django.forms.extras.widgets import SelectDateWidget

from .models import Produce


class ProduceForm(forms.ModelForm):
    class Meta:
        model = Produce
        fields = ('name', 'category', 'description', 'unit', 'price', 'stock',
                  'is_available', 'collection', 'date_from_source', 'availability')
        widgets = {'date_from_source': SelectDateWidget(),
                   'availability': SelectDateWidget()}

diadaa/users/forms.py
from django.contrib.auth import get_user_model
from django import forms


class SignupForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['phone']

    def signup(self, request, user):
        user.phone = self.cleaned_data['phone']
        user.save()

diadaa/analytics/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from diadaa.produce.models import Produce
from diadaa.logistics.models import Inventory
from diadaa.users.models import User, Member

from .charts import GenericChart, StackedBarChart
from .models import ObjectViewed


class HomeView(ListView, LoginRequiredMixin):
    queryset = User.objects.all().order_by('username')
    template_name = 'analytics/home.html'
    context_object_name = 'users'


@login_required
def home_view(request):
    template = 'analytics/home.html'
    context = {'users': User.objects.all().order_by('username')}
    return render(request, template, context)


@login_required
def user_dashboard(request, username):
    if not request.user.is_staff:
        return redirect('/403')

    user_id = User.objects.get(username=username).id
    context = {'produce_chart': None, 'produce_title': '!', 'produce_info': "This user hasn't viewed anything yet",
               'produce_caption': 'produce caption', 'rating_chart': None, 'rating_title': '!',
               'rating_info': 'This user has no rating', 'rating_caption': 'rating caption'}

    produce_viewed = ObjectViewed.objects.filter(user_id=user_id)
    if produce_viewed:
        freq = dict(produce_viewed.to_dataframe()['object_id'].value_counts())
        # this step to prevent duplicates since there could be same item from different users
        freq = {Produce.objects.get(id=obj_id).name: counts for obj_id, counts in freq.items()}.items()
        labels = [x[0] for x in freq]
        # use .item() on numpy integers to convert to native numbers else it won't be JSON serializable
        data = [x[1].item() for x in freq]
        produce_chart = GenericChart(
            data=data,
            labels=labels
        )
        produce_chart.chart_type = 'polarArea'
        context['produce_chart'] = produce_chart
        context['produce_title'] = 'items viewed by ' + username
        context['produce_info'] = 'produce description'
        context['produce_caption'] = 'produce caption'

    user_rating = Member.members.get(user_id=user_id).get_rating()

    # empty model entries are nan, not 'nan' and it's annoying
    if sum(user_rating.values()) >= 0:
        rating_chart = GenericChart(
            labels=list(user_rating.keys()),
            data=list(user_rating.values())
        )
        rating_chart.chart_type = 'bar'
        context['rating_chart'] = rating_chart
        context['rating_title'] = username + ' is rated as follows'
        context['rating_info'] = 'rating description'
        context['rating_caption'] = 'rating caption'

    # can we have plots for both demand and stock on the same graph
    inventory = Inventory.objects.all().distinct('produce_id')
    data, labels = [], []
    for produce in inventory:
        labels += [produce.produce.name]
        data += [produce.total_demand]
    inventory_chart = StackedBarChart(
        data=data,
        labels=labels
    )
    inventory_chart.chart_type = 'bar'
    context['inventory_chart'] = inventory_chart
    context['inventory_info'] = 'lala'
    context['inventory_caption'] = 'qaqa'

    return render(request, 'analytics/dashboard.html', context)

diadaa/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from diadaa.produce.models import Produce, ProduceCollection
from .cart import Cart
from .forms import CartAddProduceForm


@require_POST
def cart_add(request, produce_id):
    produce = get_object_or_404(ProduceCollection, id=produce_id)
    cart = Cart(request)
    form = CartAddProduceForm(request.POST or None)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(produce=produce,
                 quantity=cd['quantity'],
                 update_quantity=cd['quantity'])
    return redirect('cart:cart_detail')


def cart_remove(request, produce_id):
    produce = get_object_or_404(ProduceCollection, id=produce_id)
    cart = Cart(request)
    cart.remove(produce)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProduceForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'cart/cart_detail.html', {'cart': cart})

diadaa/contact/views.py
from django.conf import settings
from django.contrib import messages
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from .forms import ApplyForm, ContactForm


def apply_view(request):
    form = ApplyForm(request.POST or None)
    if form.is_valid():
        cd = form.cleaned_data
        send_mail(subject='application as an agent for {}'.format(request.user.username),
                  message=cd['message'] + '\nnational_id:{0}\ndigital_address: {1}'.format(
                      cd['national_id'], cd['digital_address']),
                  from_email=request.user.email,
                  recipient_list=[settings.EMAIL_HOST],
                  fail_silently=True)
        messages.info(request, "Thanks for applying, we'll contact you shortly" )
        return redirect(request.user)
    return render(request, 'pages/contact.html', {'form': form})


def contact_view(request):
    form = ContactForm(request.POST or None)
    if form.is_valid():
        cd = form.cleaned_data
        send_mail(subject='contact from {0} on diadaa'.format(cd['email']),
                  message=cd['message'],
                  from_email=cd['email'],
                  recipient_list=[settings.EMAIL_HOST],
                  fail_silently=True)
        messages.info(request, 'Thanks for contacting us')
        return redirect('home')
    return render(request, 'pages/contact.html', {'form': form})

diadaa/logistics/views.py
from django.views.generic import DetailView, ListView
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import TransportForm
from .models import Carrier, Transport


class TransportListView(LoginRequiredMixin, ListView):
    model = Transport
    # template_name = 'logistics/transport_list.html'
    context_object_name = 'transports'


def transport_detail_view(request, id=None):
    template_name = 'logistics/transport_list.html'
    transport = get_object_or_404(Transport, id=id)
    # object_viewed_signal.send(Member, instance=transport, request=request)
    return render(request, template_name, {'member': transport})


class TransportDetailView(LoginRequiredMixin, DetailView):
    model = Transport
    slug_field = 'vehicle_number'
    slug_url_kwarg = 'vehicle_number'


# def transport_create_view(request):
#     form = TransportForm(request.POST or None)
#     if form.is_valid():
#         produce_obj = form.save(commit=False)
#         produce_obj.owner = request.user
#         produce_obj.slug = slugify(produce_obj.name, request.user.id)
#         # quick fix. Need a way to use a date picker
#         # checkout https://github.com/pbucher/django-bootstrap-datepicker
#         produce_obj.date_from_source = timezone.now().date()
#         produce_obj.availability = timezone.now().date()
#         produce_obj.save()
#         return HttpResponseRedirect('/members/{id}'.format(id=request.user.id))
#     return render(request, 'farm_to_buyer/produce_create.html', {'form': form})

diadaa/orders/views.py
from django.shortcuts import render
from diadaa.cart.cart import Cart

from .forms import OrderCreateForm, BulkDemandForm
from .models import OrderItem
from .tasks import order_created


def order_create(request):
    cart = Cart(request)
    form = OrderCreateForm(request.POST or None)
    if form.is_valid():
        order = form.save()
        for item in cart:
            OrderItem.objects.create(order=order,
                                     produce=item['produce'],
                                     price=item['price'],
                                     quantity=item['quantity'])
        cart.clear()
        # launch asynchronous task
        order_created.delay(order.id)
        return render(request, 'orders/order_created.html', {'order': order})
    return render(request, 'orders/order_create.html', {'cart': cart, 'form': form})


# @require_POST
def bulk_demand_create(request):
    form = BulkDemandForm(request.POST or None)
    if form.is_valid():
        demand_obj = form.save(commit=False)
        demand_obj.user = request.user
        demand_obj.price = demand_obj.produce.price
        demand_obj.save()
        return render(request, 'orders/order_created.html', {'order': demand_obj})
    return render(request, 'orders/bulk_demand_create.html', {'form': form})

diadaa/templates/users/member_detail.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Member Detail{% endblock %}

{% block content %}
{% if not request.user.is_authenticated %}
{% else %}
{% endif %}
<h2>{{ member.user.username }}</h2>


 <div class="container">
	<div class="row">
		<h1>{% if category %}{{ category.name }}{% else %}Produce{% endif %}</h1>
{#        <a class="btn btn-outline-success btn-lg" href="{% url 'orders:bulk_demand_create' %}">Bulk Order</a>#}
	</div>
    <hr>
    <div class="row row-margin-bottom">
    {% for product in produce %}
        <div class="col-md-5 no-padding lib-item" data-category="view">
            <div class="lib-panel">
                <div class="row box-shadow">
                    <div class="col-md-6">
                        <a href="{{ product.get_absolute_url }}">
                          <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'images/no_image.png' %}{% endif %}">
                        </a>
                    </div>
                    <div class="col-md-6">
                        <div class="lib-row lib-header">
                            <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                            <div class="lib-header-seperator"></div>
                        </div>
                        <div class="lib-row lib-desc">
                            GHS {{ product.price }} <br>{{ product.user.member.get_region_display }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-1"></div>
    {% endfor %}
    </div>
</div>



{% if request.user.is_staff %}
<div class="controls">
    <a class="btn btn-primary" href="{% url 'analytics:dashboard' request.user.username %}" role="button">Dashboard</a>
</div>
{% endif %}
{% endblock content %}

diadaa/templates/users/member_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Members{% endblock %}

{% block content %}
<div class="container">
  <h2>Members</h2>

  <div class="list-group">
    <ol>
    {% for member in members %}
{#        {% if member != request.user.username %}#}
        <li><a href="{% url 'users:member_detail' member.user.username %}">
            {{ member.user.username }}
            </a>
      <div class="list-group-item">
        <h4>{{ member.produce_names }}</h4>
      </div>
      </li>
{#        {% endif %}#}
    {% endfor %}
    </ol>
  </div>
</div>
{% endblock content %}

diadaa/templates/users/member_type_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Members{% endblock %}

{% block content %}
<div class="container">
  <h2>Members</h2>

  <div class="list-group">
    <ol>
        <li><h4><a class="list-group-item" href="{% url 'users:member_list' %}">All</a></h4>
        <li><h4><a class="list-group-item" href="{% url 'users:agent_list' %}">Agents</a></h4>
        <li><h4><a class="list-group-item" href="{% url 'users:consumer_list' %}">Consumers</a></h4>
        <li><h4><a class="list-group-item" href="{% url 'users:farmer_list' %}">Farmers</a></h4>
        <li><h4><a class="list-group-item" href="{% url 'users:retailer_list' %}">Retailers</a></h4>
        <li><h4><a class="list-group-item" href="{% url 'users:wholesaler_list' %}">Wholesalers</a></h4>
      </li>
    </ol>
  </div>
</div>
{% endblock content %}

diadaa/templates/users/user_detail.html
{% extends "base.html" %}
{% load static i18n %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}

{% if object != request.user %}
{#    {% redirect '403.html' %}#}

{% else %}

{#{% with request.user.member.is_consumer as is_consumer %}#}
{#{% with request.user.member.is_farmer as is_farmer %}#}
{#{% with request.user.member.is_agent as is_agent %}#}
{#{% with request.user.member.is_retailer as is_retailer %}#}
{% with is_consumer=request.user.member.is_consumer is_farmer=request.user.member.is_farmer is_agent=request.user.member.is_agent is_retailer=request.user.member.is_retailer is_wholesaler=request.user.member.is_wholesaler%}

<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>



<!-- Action buttons -->
<div class="row ">

  <div class="col-sm-12">
      <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">
          {% trans 'My Info' %}
      </a>
      <a class="btn btn-primary" href="{% url 'users:member_detail' object.username %}"  role="button">
          {% trans 'My produce' %}
      </a>
      <!-- Your Stuff: Custom user template urls -->
      <a class="btn btn-primary" href="{% url 'produce:produce_create' %}"  role="button">
          {% trans 'Add produce' %}
      </a>
      {% if is_consumer or is_retailer or is_wholesaler %}
          <a class="btn btn-primary" href="{% url 'apply' %}"  role="button">
              {% trans 'Apply as an agent' %}
          </a>
      {% endif %}
  </div>

</div>
<!-- End Action buttons -->
</div>

 <div class="container" style="padding-top: 30px;">
  <div class="row">
    {% if is_consumer or is_retailer %}
        <div class="col-sm">
            <div class="card border-info" style="width: 20rem;">
              <div class="card-header">
                <h5>Recommended Produce</h5>
              </div>
                <ol class="list-group list-group-flush">
                  {% for prod in produce %}
                      <li class="list-group-item">
                          <a href="{% url 'produce:produce_detail' prod.slug %}">
                              {{ prod.name }} @ GHS {{ prod.price }}
                          </a>
                      </li>
                  {% endfor %}
                </ol>
            </div>
        </div>
    {% endif %}

    {% if is_agent or is_retailer or is_consumer %}
        <div class="col-sm">
            <div class="card border-success" style="width: 20rem;">
              <div class="card-header">
                <h5>Recommended Farmers</h5>
              </div>
                <ol class="list-group list-group-flush text-success">
                    <li class="list-group-item">Farmer 1</li>
                    <li class="list-group-item">Farmer 2</li>
                    <li class="list-group-item">Farmer 3</li>
                </ol>
            </div>
        </div>
    {% endif %}
    {% if is_farmer or is_agent %}
        <div class="col-sm">
            <div class="card border-danger" style="width: 20rem;">
              <div class="card-header">
                <h5>Transports close to you</h5>
              </div>
                <ol class="list-group list-group-flush text-danger">
                    <li class="list-group-item">Transport 1 departs at xxx</li>
                    <li class="list-group-item">Transport 2 departs at xxx</li>
                    <li class="list-group-item">Transport 3 departs at xxx</li>
                </ol>
            </div>
        </div>
    {% endif %}
  </div>
</div>
{% endwith %}
{#{% endwith %}#}
{#{% endwith %}#}
{#{% endwith %}#}

{% endif %}


{% endblock content %}

diadaa/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
    <div class="container-fluid">
      <h1>{{ user.username }}</h1>
      <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="control-group">
          <div class="controls">
            <button type="submit" class="btn">Update</button>
          </div>
        </div>
      </form>
    </div>
{% endblock %}

diadaa/templates/users/user_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Members{% endblock %}

{% block content %}
<div class="container">
  <h2>Users</h2>

  <div class="list-group">
    {% for user in user_list %}
      <a href="{% url 'users:detail' user.username %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ user.username }}</h4>
      </a>
    {% endfor %}
  </div>
</div>
{% endblock content %}