config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from diadaa.contact import views as contact_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('diadaa.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^analytics/', include('diadaa.analytics.urls', namespace='analytics')),
    # url(r'^apply/', include('diadaa.contact.urls_apply', namespace='apply')),
    url(r'apply/', contact_views.apply_view, name='apply'),
    url(r'^cart/', include('diadaa.cart.urls', namespace='cart')),
    # url(r'^contact/', include('diadaa.contact.urls_contact', namespace='contact')),
    url(r'contact/', contact_views.contact_view, name='contact'),
    url(r'^orders/', include('diadaa.orders.urls', namespace='orders')),
    url(r'^produce/', include('diadaa.produce.urls', namespace='produce')),
    url(r'^logistics/', include('diadaa.logistics.urls', namespace='logistics')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

diadaa/cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<produce_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<produce_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

diadaa/logistics/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    # url(r'^carrier/$', views.TransportListView.as_view(), name='carrier_list'),
    url(r'^transport/$', views.TransportListView.as_view(), name='transport_list'),
    url(r'^transport/(?P<vehicle_number>[-\w]+/?)$', views.TransportDetailView.as_view(), name='transport_detail'),
]

diadaa/orders/urls.py
from django.conf.urls import url
from . import views


urlpatterns = (
    url(r'^bulk/$', views.bulk_demand_create, name='bulk_demand_create'),
    url(r'^create/$', views.order_create, name='order_create'),
)

diadaa/produce/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.ProduceCollectionListView.as_view(), name='produce_collection_list'),
    # url(r'^$', views.ProduceListView.as_view(), name='produce_list'),
    url(r'^categories/$', views.CategoryListView.as_view(), name='category_list'),
    url(r'^categories/(?P<slug>[-\w]+/?)$', views.CategoryDetailView.as_view(), name='category_detail'),
    url(r'^add_produce$', views.produce_create_view, name='produce_create'),
    # url(r'^~(?P<slug>[-\w]+/?)$', views.produce_detail_view, name='produce_detail'),
    url(r'^(?P<name>[-\w]+/?)$', views.produce_collection_detail_view, name='produce_collection_detail'),
    url(r'^~(?P<slug>[-\w]+/?)$', views.ProduceDetailView.as_view(), name='produce_detail'),
    url(r'^~(?P<slug>[-\w]+/?)/update/$', views.ProduceUpdateView.as_view(), name='produce_update'),
]

diadaa/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.MemberTypeListView.as_view(), name='member_type_list'),
    url(r'^~redirect/$', views.UserRedirectView.as_view(), name='redirect'),
    url(r'^~update/$', views.UserUpdateView.as_view(), name='update'),
    url(r'^all/$', views.MemberListView.as_view(), name='member_list'),
    url(r'^agents/$', views.AgentListView.as_view(), name='agent_list'),
    url(r'^consumers/$', views.ConsumerListView.as_view(), name='consumer_list'),
    url(r'^farmers/$', views.FarmerListView.as_view(), name='farmer_list'),
    url(r'^retailers/$', views.RetailerListView.as_view(), name='retailer_list'),
    url(r'^wholesalers/$', views.WholesalerListView.as_view(), name='wholesaler_list'),
    url(r'^(?P<username>[\w.@+-]+)/$', views.UserDetailView.as_view(), name='user_detail'),
    url(r'^~(?P<username>[\w.@+-]+)/$', views.member_detail_view, name='member_detail'),
]

diadaa/logistics/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models import Q
from django.db.models.signals import post_save
from django.dispatch import receiver

from diadaa.produce.models import Produce

from .services import vehicle_directory_path


# class BusStation(models.Model):
#     pass


class Carrier(models.Model):
    CARRIER_CHOICE = (
        ('L', 'Individual'),
        ('M', 'Private vehicle'),
        ('H', 'Bus driver'),
    )
    name = models.CharField(max_length=100)
    carrier_type = models.CharField(max_length=1, choices=CARRIER_CHOICE, default='L', blank=False)
    carrier_phone = models.CharField(max_length=17)
    description_of_goods = models.TextField(default='')
    agree_to_terms = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Inventory(models.Model):
    # change this to diaDaaInventory
    produce = models.ForeignKey(Produce,
                                limit_choices_to=Q(user__username='diadaa'),
                                on_delete=models.CASCADE)

    def __str__(self):
        return self.produce.name

    @property
    def demand_locations(self):
        # TODO: demand isn't always from bulk demand
        return ", ".join([produce.user.member.get_region_display() for produce in self.produce.collection.bulk_items.all()])

    @property
    def stock(self):
        return self.produce.total_stock

    @property
    def total_demand(self):
        # TODO: demand isn't always from bulk demand
        return sum([produce.quantity for produce in self.produce.collection.bulk_items.all()])

    def get_absolute_url(self):
        # TODO: give staff/agent a view outside backend to see what is needed
        pass

    class Meta:
        verbose_name_plural = 'Inventories'


@receiver(post_save, sender=Produce)
def create_inventory_item(**kwargs):
    if kwargs['created'] and kwargs['instance'].user.username == 'diadaa':
    # and instance.name or instance.collection.name isn't in Inventory objects
            Inventory.objects.create(produce=kwargs['instance'])


class Transport(models.Model):
    REGION_CHOICES = (
      ('ar', 'Ashanti Region'),
      ('ba', 'Brong Ahafo Region'),
      ('cr', 'Central Region'),
      ('er', 'Eastern Region'),
      ('ga', 'Greater Accra'),
      ('nr', 'Northern Region'),
      ('ue', 'Upper East Region'),
      ('uw', 'Upper West Region'),
      ('vr', 'Volta Region'),
      ('wr', 'Western Region'),
    )
    vehicle_number = models.CharField(max_length=20, blank=False)
    name_of_driver = models.CharField(max_length=100)
    departure_region = models.CharField(max_length=3,  choices=REGION_CHOICES)
    departure_location = models.CharField(max_length=100)
    time_of_departure = models.DateTimeField()
    arrival_region = models.CharField(max_length=3,  choices=REGION_CHOICES)
    arrival_location = models.CharField(max_length=100)
    eta = models.TimeField(verbose_name='estimated time of arrival')
    transport_route = models.CharField(max_length=200)
    available_stops = models.CharField(max_length=200)
    image = models.ImageField(upload_to=vehicle_directory_path, default='')
    capacity = models.FloatField(blank=False)
    # cost_per_weight
    availability = models.DateTimeField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.vehicle_number

    def get_absolute_url(self):
        return reverse('logistics:transport_detail', kwargs={'vehicle_number': self.vehicle_number})

diadaa/produce/models.py
from decimal import Decimal
from math import ceil

from django.core.urlresolvers import reverse
from django.db import models
from django.db.models import Avg, Max, Min

from diadaa.users.models import User

from .metrics import distance_duration
from .services import produce_directory_path


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('produce:category_detail', kwargs={'slug': self.slug})

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'


class ProduceCollection(models.Model):
    name = models.CharField(max_length=100, unique=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    @property
    def image(self):
        # TODO: if there's nothing we need to return some blank image
        try:
            image = self.produce_set.exclude(image='')[0].image.url
        except:
            image = None
        return image

    def produce_owners(self):
        return ", ".join([p.user.username for p in self.produce_set.all()])

    def cost_from_location(self, destination):
        return distance_duration((self.user.member.location, self.user.member.region), destination)

    # we need to enforce a common unit else this isn't possible. we could also have different conversions
    @property
    def min_avg_max(self):
        return self.price_min, self.price_avg, self.price_max

    def closest_source_cost(self, destination, demand_qty, units=None, t_rate=0.0001, q_rate=0.005):
        # we may use weight rate rather than quantity rate
        # if demand_qty is less than closest source stock, then that'll be the cost, else we do something else
        # stock -> {id: (stock, location, region)}
        # we need {id: (stock, location, region, cost per unit item)
        # [(id, stock, location, region, distance value, distance text, time value, time text, transportation cost)]
        # TODO: we use an upper bound for the first on the cost assuming the second source might meet demand.
        # TODO: This is an optimization problem that needs to be solved. One might think a greedy answer is best because
        # TODO: you'll just need to go for the closest source but prices will also come into play and the rates of
        # TODO: moving the items

        d = sorted(
            [(k, *v, *distance_duration(v[1:], destination, units=units)) for k, v in self.__stock.items()],
            key=lambda x: x[4])
        if demand_qty < d[0][1]:
            return (*d[0], ceil(float(d[0][4])*t_rate + demand_qty*q_rate))
        else:
            return (*d[1], ceil(float(d[1][4])*t_rate + demand_qty*q_rate))

    @property
    def price(self):
        return self.price_max

    # def transportation_cost(self, source, quantity):
    #     # TODO: price will be based on several factors. 1st will be cost of transportation
    #     # TODO: we use the max for now
    #     # TODO: fictitious pricing. we might actually need the weights
    #
    #     cs = Decimal(self.closest_source(source, quantity)[4])
    #     quantity = Decimal(quantity)
    #     return Decimal('0.005')*cs * Decimal('0.1')*quantity

    @property
    def price_min(self):
        return self.produce_set.all().aggregate(r=Min('price'))['r'] or 0

    @property
    def price_avg(self):
        return self.produce_set.all().aggregate(r=Avg('price'))['r'] or 0

    @property
    def price_max(self):
        return self.produce_set.all().aggregate(r=Max('price'))['r'] or 0

    def get_absolute_url(self):
        return reverse('produce:produce_collection_detail', kwargs={'name': self.name})

    @property
    def __stock(self):
        # we need to know the stock from each location
        return {p.user_id: (p.stock, p.user.member.location, p.user.member.get_region_display())
                for p in self.produce_set.all()}

    @property
    def total_stock(self):
        return sum([s[0] for s in self.__stock.values()])

    @property
    def unit(self):
        # TODO: we need to have a unit-unit conversion matrix
        # TODO: for now I'm gonna use the first unit. then we could then be able to switch to the desired units
        try:
            unit = self.produce_set.first().get_unit_display()
        except:
            unit = None
        return unit

    @property
    def owner_regions(self):
        return ", ".join([p.user.member.get_region_display()[:-7] for p in self.produce_set.all()])


class Produce(models.Model):
    UNIT_CHOICES = (
        ('bg', 'Bag'),
        ('bs', 'Basket'),
        ('bx', 'Box'),
        ('co', 'Container'),
        ('cp', 'Cups'),
        ('cr', 'Crate'),
        ('g', 'Gram'),
        ('gl', 'Gallon'),
        ('kg', 'Kilogram'),
        ('lb', 'Pounds'),
        ('Nm', 'Number'),
        ('ol', 'Olonka'),
        ('O', 'Other')
    )
    user = models.ForeignKey(User, related_name='produce', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)
    category = models.ForeignKey(Category)
    collection = models.ForeignKey(ProduceCollection)
    image = models.ImageField(upload_to=produce_directory_path, blank=True)
    description = models.CharField(max_length=100)
    # standard unit and non standard unit
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Price per unit GHS')
    unit = models.CharField(max_length=3, choices=UNIT_CHOICES)
    stock = models.PositiveIntegerField()
    date_from_source = models.DateField()
    is_available = models.BooleanField(default=True)
    availability = models.DateField(verbose_name="Available from")
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-timestamp',)
        index_together = (('id', 'slug'),)
        verbose_name_plural = "produce"

    def __str__(self):
        return self.name + ' from ' + self.user.username

    def get_absolute_url(self):
        return reverse('produce:produce_detail', kwargs={'slug': self.slug})

diadaa/cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProduceForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

diadaa/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from diadaa.produce.models import Produce, ProduceCollection
from .cart import Cart
from .forms import CartAddProduceForm


@require_POST
def cart_add(request, produce_id):
    produce = get_object_or_404(ProduceCollection, id=produce_id)
    cart = Cart(request)
    form = CartAddProduceForm(request.POST or None)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(produce=produce,
                 quantity=cd['quantity'],
                 update_quantity=cd['quantity'])
    return redirect('cart:cart_detail')


def cart_remove(request, produce_id):
    produce = get_object_or_404(ProduceCollection, id=produce_id)
    cart = Cart(request)
    cart.remove(produce)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProduceForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'cart/cart_detail.html', {'cart': cart})

diadaa/contact/views.py
from django.conf import settings
from django.contrib import messages
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from .forms import ApplyForm, ContactForm


def apply_view(request):
    form = ApplyForm(request.POST or None)
    if form.is_valid():
        cd = form.cleaned_data
        send_mail(subject='application as an agent for {}'.format(request.user.username),
                  message=cd['message'] + '\nnational_id:{0}\ndigital_address: {1}'.format(
                      cd['national_id'], cd['digital_address']),
                  from_email=request.user.email,
                  recipient_list=[settings.EMAIL_HOST],
                  fail_silently=True)
        messages.info(request, "Thanks for applying, we'll contact you shortly" )
        return redirect(request.user)
    return render(request, 'pages/contact.html', {'form': form})


def contact_view(request):
    form = ContactForm(request.POST or None)
    if form.is_valid():
        cd = form.cleaned_data
        send_mail(subject='contact from {0} on diadaa'.format(cd['email']),
                  message=cd['message'],
                  from_email=cd['email'],
                  recipient_list=[settings.EMAIL_HOST],
                  fail_silently=True)
        messages.info(request, 'Thanks for contacting us')
        return redirect('home')
    return render(request, 'pages/contact.html', {'form': form})

diadaa/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

diadaa/templates/base.html
{% load static i18n compress%}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Diadaa{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    {% block css %}
    <!-- Bootstrap core CSS -->
    <link href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "fonts/fontawesome.min.css" %}" rel="stylesheet">

    {% compress css %}
    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    {% endcompress %}
    {% endblock %}
  </head>
  <body>

{#  Courtesy of https://github.com/kjdion84/bsadmin #}
<nav class="navbar navbar-expand navbar-dark bg-primary">
    <a class="sidebar-toggle text-light mr-3"><i class="fa fa-bars"></i></a>
    <a class="navbar-brand" href="{% url 'home' %}"><i class="fa fa-at"></i>diaDaa</a>

    <div class="navbar-collapse collapse">
        <ul class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown">
                        <i class="fa fa-user"></i> {{ request.user.username }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'users:user_detail' request.user.username  %}">
                            {% trans "My Profile" %}
                        </a>
                        <a class="dropdown-item" href="{% url 'account_logout' %}">
                            {% trans "Sign Out" %}
                        </a>
                    </div>
                </li>
            {% else %}
                <li class="nav-item ">
                    <a class="nav-link" href="{% url 'account_login' %}">
                        <i class="fa fa-user"></i> {% trans 'Sign in' %}
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_signup' %}">
                        <i class="fa fa-user"></i> {% trans 'Sign Up' %}
                    </a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

<div class="d-flex">
    <nav class="sidebar bg-dark">
        <ul class="list-unstyled">
            <li><a href="{% url 'about' %}"><i class="fa fa-fw fa-info-circle"></i>About</a></li>
            <li><a href="{% url 'contact' %}"><i class="fa fa-fw fa-phone-square"></i>Contact Us</a></li>
            {% if request.user.is_authenticated %}
            <li>
                <a href="#submenu1" data-toggle="collapse"><i class="fa fa-fw fa-cube"></i> Produce</a>
                <ul id="submenu1" class="list-unstyled collapse">
{#                    <li><a href="{% url 'produce:produce_list' %}">Produce List</a></li>#}
                    <li><a href="{% url 'produce:produce_collection_list' %}">Produce</a></li>
                    <li><a href="{% url 'produce:category_list' %}">Produce categories</a></li>
                    <li><a href="{% url 'orders:bulk_demand_create' %}">Bulk Order</a></li>
                </ul>
            </li>
            {% if request.user.is_staff %}
            <li>
                <a href="#submenu2" data-toggle="collapse"><i class="fa fa-fw fa-address-card"></i> Admin</a>
                <ul id="submenu2" class="list-unstyled collapse">
                    <li><a href="{% url 'analytics:home' %}">Analytics</a></li>
                    <li><a href="{% url 'users:member_type_list' %}">Members</a></li>
                    <li><a href="{% url 'logistics:transport_list' %}">Transport</a></li>
                </ul>
            </li>
            {% endif %}
{#            <li><a href="{% url 'apply' %}"><i class="fa fa-fw fa-angle-right"></i>#}
{#                {% trans 'Apply as an agent' %}#}
{#            </a></li>#}
{#            <li><a href="#"><i class="fa fa-fw fa-link"></i> Sidebar Link</a></li>#}
{#            <li><a href="#"><i class="fa fa-fw fa-link"></i> Sidebar Link</a></li>#}
            {% endif %}
        </ul>
    </nav>

    <div class="content p-4">
      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}
      {% block content %}{% endblock content %}
    </div>
</div>




    <!-- Footer -->
{#    <footer class="py-4 bg-dark">#}
{#      <div class="container">#}
{#        <p class="m-0 text-center text-white">Copyright &copy; diaDaa 2018</p>#}
{#      </div>#}
{#      <!-- /.container -->#}
{#    </footer>#}

    {% block modal %}{% endblock modal %}


    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
    <!-- Plugin JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static "vendor/bootstrap/js/bootstrap.min.js" %}"></script>

    <!-- Custom JavaScript for this theme -->
      <!-- place project specific Javascript in this file -->
      {% compress js %}
      <script src="{% static 'js/project.js' %}"></script>
      <script src="{% static 'vendor/Chart.js/Chart.bundle.min.js' %}"></script>
      {% endcompress %}

    {% endblock javascript %}

  </body>
</html>